### PR TITLE
fix: only apply to modules

### LINKED ISSUE #1: False-negative on JSON import
This could potentially affect other non-script imports?

I have in my code this import:

```js
import mockObjects from './mock-data.json' assert { type: 'json' }
```

The plugin complains and when "fixed", it changes that line into

```js
import mockObjects from './mock-data.json.js' assert { type: 'json' }
```

I think that rule should only apply to some pattern, like`/.+(t|j)s(x)?/` by default. Possibly configurable.

### PR DESCRIPTION
**Pull request by tpluscode**
This is an attempt to fix #1 

I would like to add some tests but this is my first time writing code for an eslint plugins and not sure how to proceed

About the change itself, it find the actual module in the filesystem and applies to rule only when a module exists with one of the extensions

For example, given code like

```js
import foo from './bar.json'
```

An error will be shown when there is a source file `bar.json.js` or `bar.json.ts` but not when it's simply `bar.json`

I'm not sure if it's correct to also include `jsx` and `tsx` in the extensions to check.

### CODE REVIEW

**Comment by tpluscode** [comment]
Ping @ jordansexton ?

**Comment by tpluscode** [comment]
Ping @jordansexton ?

**Comment by jordansexton** [comment]
@tpluscode Ah, thanks for the ping, didn't see this. Will review today.

**Comment by tpluscode** [comment]
Super, thanks

**Review by jordansexton — COMMENTED** [review]
Hmm, I don't think we need to actually check for the existence of the file, do we? Importing a file that doesn't exist should be allowed, as long as the required extension (`.js`) is provided. This should typically get handled by a different eslint rule, which will have a more helpful error description.

I don't know if this is a good idea or not, but a possible fix could be to look for an extension at the end of the filename, and if one is there, look for a corresponding file at that full path. If the file exists, don't enforce the `.js` extension, but just allow any extension to be imported, and assume the dev knows what they are doing.

**Comment by tpluscode** [comment]
Aha, I wrote that lengthy reply before realising I misunderstood your point. 😅

Yes, you're right, a file which does no exist should have the `.js` suffix added which will inevitably lead to a different rule kicking in, or TS compiler error, ot runtime loader error. Not this plugin's concern

There are quite some cases, some of which are not handled by this PR not the base branch. It would really be good to add unit tests but I do not have experience testing eslint rules. Do you?

**Comment by tpluscode** [comment]
What do you think about my updated code @jordansexton ?

File: index.js [hunk 1]
```diff
@@ -17,9 +22,9 @@ module.exports = {
                     const source = node.source;
                     if (!source) return;
                     const value = source.value;
-                    if (!value) return;
+                    if (!value || !value.startsWith('.') || value.endsWith('.js')) return;
 
-                    if (value.startsWith('.') && !value.endsWith('.js')) {
+                    if (!existsSync(resolve(dirname(context.getFilename()), value))) {
```
Comment (jordansexton) [inline index.js:27]: I still don't see why we need to check for the file existence here.

File: index.js [hunk 2]
```diff
@@ -1,3 +1,8 @@
+const { existsSync } = require('fs')
+const { dirname, resolve } = require('path')
+
+const extensions = ['js', 'ts', 'jsx', 'tsx']
```
Comment (jordansexton) [inline index.js:4]: These declared extensions aren't used.

**Review by jordansexton — COMMENTED** [review]
I reviewed again, but it looks like the first review wasn't fully addressed.

Looking @ https://github.com/solana-labs/eslint-plugin-require-extensions/issues/1, it seems that the problem is that imports of files with explicit extensions (.json, maybe others?) should not have .js extensions added.

Is this right? If so, it seems like the fix could be as simple as checking for a file extension on the import. If it's there, and perhaps if it's not .js/x or .ts/x, we don't do anything with that import. I don't think we care about the actual file, right?

File: index.js (hunk 2 above)
Comment (tpluscode) [reply index.js]: Right. Sorry

File: index.js (hunk 1 above)
Comment (jordansexton) [reply index.js:25]: Ah, got it, seems reasonable. Thanks!

**Comment by jordansexton** [comment]
Published in v0.1.2! Please let me know if it works well for you, and thank you for working on this!

**Comment by tpluscode** [comment]
Super, thanks for releasing
